
/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/


#ifndef DEM_CFG_ENVDATAELEMENT_H
#define DEM_CFG_ENVDATAELEMENT_H

#include "Std_Types.h"
#include "Dem_Cfg_EnvDataElement_DataSize.h"


#define DEM_CFG_ENV_DATAELEMENTS_EXTERN_AVAILABILITY   STD_ON
#define DEM_CFG_ENV_DATAELEMENTS_INTERN_AVAILABILITY  STD_ON

#define DEM_CFG_READDEM_AGINGCTR_UPCNT_SUPPORTED                         TRUE
#define DEM_CFG_READDEM_AGINGCTR_DOWNCNT_SUPPORTED                       FALSE
#define DEM_CFG_READDEM_OCCCTR_SUPPORTED                                 FALSE
#define DEM_CFG_READDEM_OVFLIND_SUPPORTED                                FALSE
#define DEM_CFG_READDEM_SIGNIFICANCE_SUPPORTED                           FALSE
#define DEM_CFG_READDEM_MONITOR_DATA_0_SUPPORTED                         FALSE
#define DEM_CFG_READDEM_MONITOR_DATA_1_SUPPORTED                         FALSE
#define DEM_CFG_READDEM_EVENT_ID_SUPPORTED                               FALSE
#define DEM_CFG_READDEM_CURRENT_FDC_SUPPORTED                            TRUE
#define DEM_CFG_READDEM_MAX_FDC_DURING_CURRENT_CYCLE_SUPPORTED           FALSE
#define DEM_CFG_READDEM_MAX_FDC_SINCE_LAST_CLEAR_SUPPORTED               TRUE
#define DEM_CFG_READDEM_CYCLES_SINCE_FIRST_FAILED_SUPPORTED              TRUE
#define DEM_CFG_READDEM_CYCLES_SINCE_LAST_FAILED_SUPPORTED               TRUE
#define DEM_CFG_READDEM_CYCLES_SINCE_LAST_FAILED_EXCLUDING_TNC_SUPPORTED   FALSE
#define DEM_CFG_READDEM_FAILED_CYCLES_SUPPORTED                          TRUE
#define DEM_CFG_READDEM_PRJ_SPECIFIC_DATA_ON_RETRIEVE_SUPPORTED          FALSE
#define DEM_CFG_READDEM_PRJ_SPECIFIC_DATA_ON_REPORT_SUPPORTED            FALSE
#define DEM_CFG_READDEM_MIL_DIST_SUPPORTED                               FALSE
#define DEM_CFG_READDEM_WARM_UPS_SUPPORTED                               FALSE
#define DEM_CFG_READDEM_CLR_DIST_SUPPORTED                               FALSE
#define DEM_CFG_READDEM_MIL_TIME_SUPPORTED                               FALSE
#define DEM_CFG_READDEM_CLR_TIME_SUPPORTED                               FALSE
#define DEM_CFG_DATAELEMENT_LASTFAILEDSINCELASTFAILEDEXCLUDINGTNC_INCLUDESFAILEDCYCLE    TRUE

#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0X217D  1
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0X217E  2
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0X21AD  3
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0X330C  4
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD11C  5
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD905  6
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD906  7
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD909  8
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD90A  9
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD00  10
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD01  11
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD02  12
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD06  13
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD07  14
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD0A  15
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD0C  16
#define DEM_DATAELEM_SR_EDR_RECORD_TIME_STAMP_22_TIME_STAMP_22  17
#define DEM_DATAELEM_SR_EDR_RECORD_TIME_STAMP_23_TIME_STAMP_23  18
#define DEM_DATAELEM_OPERATIONCYCLE_1       19
#define DEM_DATAELEM_OPERATIONCYCLE_2       20
#define DEM_DATAELEM_OPERATIONCYCLE_3       21
#define DEM_DATAELEM_OPERATIONCYCLE_4       22
#define DEM_DATAELEM_DTCFAULTDETECTIONCOUNTER  23
#define DEM_DATAELEM_MAX_DTC_FAULTDETECTIONCNT_SINCELASTCLEAR  24

#define DEM_CFG_ENV_DATAELEMENTS \
{ \
   { DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR)  DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) 0, FALSE } \
        ,{ &Snapshot_DataFuc_Read217D, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0X217D , FALSE } \
        ,{ &Snapshot_DataFuc_Read217E, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0X217E , FALSE } \
        ,{ &Snapshot_DataFuc_Read21AD, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0X21AD , FALSE } \
        ,{ &Snapshot_DataFuc_Read330C, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0X330C , FALSE } \
        ,{ &Snapshot_DataFuc_ReadD11C, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD11C , FALSE } \
        ,{ &Snapshot_DataFuc_ReadD905, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD905 , FALSE } \
        ,{ &Snapshot_DataFuc_ReadD906, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD906 , FALSE } \
        ,{ &Snapshot_DataFuc_ReadD909, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD909 , FALSE } \
        ,{ &Snapshot_DataFuc_ReadD90A, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD90A , FALSE } \
        ,{ &Snapshot_DataFuc_ReadDD00, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD00 , FALSE } \
        ,{ &Snapshot_DataFuc_ReadDD01, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD01 , FALSE } \
        ,{ &Snapshot_DataFuc_ReadDD01, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD02 , FALSE } \
        ,{ &Snapshot_DataFuc_ReadDD06, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD06 , FALSE } \
        ,{ &Snapshot_DataFuc_ReadDD07, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD07 , FALSE } \
        ,{ &Snapshot_DataFuc_ReadDD0A, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD0A , FALSE } \
        ,{ &Snapshot_DataFuc_ReadDD0C, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD0C , FALSE } \
        ,{ &Extended_Data_ReadFnc_stamp22, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_SR_EDR_RECORD_TIME_STAMP_22_TIME_STAMP_22 , FALSE } \
        ,{ &Extended_Data_ReadFnc_stamp23, DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_SR_EDR_RECORD_TIME_STAMP_23_TIME_STAMP_23 , FALSE } \
   ,{ DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) &Dem_ReadCyclesSinceLastFailed, DemConf_DemDataElementDataSize_DEM_DATAELEM_OPERATIONCYCLE_1 , TRUE } \
   ,{ DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) &Dem_ReadAgingCtrUpCnt, DemConf_DemDataElementDataSize_DEM_DATAELEM_OPERATIONCYCLE_2 , TRUE } \
   ,{ DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) &Dem_ReadCyclesSinceFirstFailed, DemConf_DemDataElementDataSize_DEM_DATAELEM_OPERATIONCYCLE_3 , TRUE } \
   ,{ DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) &Dem_ReadFailedCycles, DemConf_DemDataElementDataSize_DEM_DATAELEM_OPERATIONCYCLE_4 , TRUE } \
   ,{ DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) &Dem_ReadCurrentFDC, DemConf_DemDataElementDataSize_DEM_DATAELEM_DTCFAULTDETECTIONCOUNTER , TRUE } \
   ,{ DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) &Dem_ReadMaxFdcSinceLastClear, DemConf_DemDataElementDataSize_DEM_DATAELEM_MAX_DTC_FAULTDETECTIONCNT_SINCELASTCLEAR , TRUE } \
}

#define DEM_CFG_ENV_DATAELEMENTS_ARRAYLENGTH      (24+1)


#endif


