
/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/


#ifndef DEM_CFG_DEB_H
#define DEM_CFG_DEB_H


#include "Std_Types.h"

/* ---------------------------------------- */
/* DEM_CFG_DEBMONINTBASE                    */
/* ---------------------------------------- */
#define DEM_CFG_DEBMONINTERNAL_OFF  STD_OFF
#define DEM_CFG_DEBMONINTERNAL_ON   STD_ON
#define DEM_CFG_DEBMONINTERNAL  DEM_CFG_DEBMONINTERNAL_OFF

#define DEM_CFG_PRJSPECIFIC_DEB_OPTIMIZATION_ON STD_ON
#define DEM_CFG_PRJSPECIFIC_DEB_OPTIMIZATION_OFF STD_OFF
#define DEM_CFG_PRJSPECIFIC_DEB_OPTIMIZATION DEM_CFG_PRJSPECIFIC_DEB_OPTIMIZATION_OFF




/* ---------------------------------------- */
/* DEM_CFG_DEBARTIMEBASE                    */
/* ---------------------------------------- */
#define DEM_CFG_DEBARTIMEBASE_OFF  STD_OFF
#define DEM_CFG_DEBARTIMEBASE_ON   STD_ON
#define DEM_CFG_DEBARTIMEBASE  DEM_CFG_DEBARTIMEBASE_OFF


/* ---------------------------------------- */
/* DEM_CFG_DEBCOUNTERBASEDCLASS             */
/* ---------------------------------------- */
#define DEM_CFG_DEBCOUNTERBASECLASS_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS  DEM_CFG_DEBCOUNTERBASECLASS_ON

#define DEM_CFG_LIMIT_RELEVANTFOR_JUMPING_OFF  STD_OFF
#define DEM_CFG_LIMIT_RELEVANTFOR_JUMPING_ON   STD_ON
#define DEM_CFG_LIMIT_RELEVANTFOR_JUMPING DEM_CFG_LIMIT_RELEVANTFOR_JUMPING_OFF

#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT 32767
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MINLIMIT (-32768)
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPUP_ENABLED TRUE
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPUP_VALUE 0
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPDOWN_ENABLED TRUE
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPDOWN_VALUE 0

#define DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD  DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD  DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE  DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE  DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN  DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP  DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP_ON

#define DEMRB_DEBOUNCECOUNTERSETS_SIZE                                 2
/** Offset of the CounterSet Id where the custom counter sets start */
#define DEMRB_DEBOUNCECOUNTERSETS_CUSTOMSETSOFFSET                     2

#define DemConf_DemRbDebounceCounterSet_Standard                       0
#define DemConf_DemRbDebounceCounterSet_Alternative                    1

#define DEM_CFG_DEBCOUNTERBASECLASS_PARAMSET_LENGTH 4



/*                 				ISJDOWN             ISJUP               MINLIMIT                      MAXLIMIT                      JDOWNValue          JUPValue            FDC_THRESHOLD       SUSPICIOUS_THRESHOLD STEPUP             STEPDOWN             */

#define DEM_CFG_DEBCOUNTERCLASS_PARAMSETS \
{ \
  { /* Default Debouncing Parameters */ \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -128,                         127,                          0,                  0,                  26,                 DEM_MAXSINT16,      13,                 -13                 ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -128,                         127,                          0,                  0,                  126,                DEM_MAXSINT16,      127,                -128                ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -128,                         127,                          0,                  0,                  6,                  DEM_MAXSINT16,      3,                  -6                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -128,                         127,                          0,                  0,                  4,                  DEM_MAXSINT16,      4,                  -128                ), \
}, \
  { /* Alternative Debouncing Parameters */  \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -128,                         127,                          0,                  0,                  26,                 DEM_MAXSINT16,      13,                 -13                 ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -128,                         127,                          0,                  0,                  126,                DEM_MAXSINT16,      127,                -128                ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -128,                         127,                          0,                  0,                  6,                  DEM_MAXSINT16,      3,                  -6                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -128,                         127,                          0,                  0,                  4,                  DEM_MAXSINT16,      4,                  -128                ), \
  }, \
}

#define DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13     0u
#define DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127            1u
#define DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE3              2u
#define DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE4              3u


#define DEM_DEBPARAM_IDX_DTC_1A0683_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_452654_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_452954_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_452A62_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_502D71_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_505602_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_505662_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_505696_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_516A62_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_600C96_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_9E2B04_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_9E2B44_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_9E2B45_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_9E2B49_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_9E2B4B_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_C12182_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_C15182_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_C15982_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_C16882_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_C29682_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_D10382_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_D14B51_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_D14C51_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_D15282_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_D15283_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_D44D82_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_DC1A88_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE4
#define DEM_DEBPARAM_IDX_DTC_DCC388_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE4
#define DEM_DEBPARAM_IDX_DTC_E01104_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_E01149_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_E01196_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_E30055_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_E30056_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_E71883_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_E72783_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_E72F81_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_E72F83_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_E7B182_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_E7B283_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_E7B383_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_EC3281_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_EC3481_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_EC3681_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_EC4281_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_ECEB81_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_ED3283_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_ED3383_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_ED3683_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_ED3983_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_ED4183_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_ED5A83_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_ED7983_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_ED9683_EVENT               DEM_DEBPARAMCLASS_IDX_DEBCNTBAS_COUNTER_BASED_13
#define DEM_DEBPARAM_IDX_DTC_EE0368_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE3
#define DEM_DEBPARAM_IDX_DTC_EE0468_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE3
#define DEM_DEBPARAM_IDX_DTC_EE0B68_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE3
#define DEM_DEBPARAM_IDX_DTC_EE0C68_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE3
#define DEM_DEBPARAM_IDX_DTC_F00004_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_F00044_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_F00045_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_F00049_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_F0004B_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_F00068_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_F00093_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE127
#define DEM_DEBPARAM_IDX_DTC_F00362_EVENT               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCE_BASE3


#define DEM_CFG_DEB_DEFINE_ALL_PARAMSETS \
static const Dem_DebCounterBaseClass_ParamSet  Dem_Cfg_DebCounterBaseClass_Paramsets[DEMRB_DEBOUNCECOUNTERSETS_SIZE][DEM_CFG_DEBCOUNTERBASECLASS_PARAMSET_LENGTH] = DEM_CFG_DEBCOUNTERCLASS_PARAMSETS; \


#define  DEM_CFG_DEB_CLASSES \
{ \
   { \
      NULL_PTR, \
      NULL_PTR, \
      NULL_PTR, \
      0, \
      NULL_PTR \
   } \
   ,{ \
      &Dem_DebCounterBaseClass_GetLimits, \
      NULL_PTR, \
      &Dem_Cfg_DebCounterBaseClass_Paramsets[DemConf_DemRbDebounceCounterSet_Standard], \
      DEM_CFG_DEBCOUNTERBASECLASS_PARAMSET_LENGTH, \
      &Dem_DebCounterBaseClass_Filter \
   } \
}

#define  DEM_CFG_DEB_NUMBEROFCLASSES  2

#define DEM_DEBMETH_IDX_ARCTRBASECLASS      (1u)





/* Support Debouncer Reset After StorageCondition */
#define DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO_OFF                                    0u
#define DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO_ACCORDING_DEBOUNCEBEHAVIOR             1u

#define DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO           DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO_OFF


#endif


