
/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/


#ifndef DEM_CFG_ENVDID_H
#define DEM_CFG_ENVDID_H

#define DEM_CFG_ENVDID2DATAELEMENT \
{ \
   DEM_DATAELEM_DEMDATAELEMENTCLASS_0X21AD,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0X217D,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0X217E,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD11C,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0X330C,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD905,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD909,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD906,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD01,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD00,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD90A,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD02,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD0A,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD07,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD06,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD0C,                                   /* DidClass_DID_0x2000 */    \
   DEM_DATAELEM_DEMDATAELEMENTCLASS_0X217D,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0X217E,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0X21AD,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0X330C,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD11C,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD905,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD906,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD909,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XD90A,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD00,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD01,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD02,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD06,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD07,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD0A,   DEM_DATAELEM_DEMDATAELEMENTCLASS_0XDD0C,                                   /* DidClass_DID_0x2100 */    \
   0 \
}


#define DEM_DID_DIDCLASS_DID_0X2000         1
#define DEM_DID_DIDCLASS_DID_0X2100         2


#define DEM_CFG_ENVDID \
{ \
   { 0, 0 } \
   ,{ 16, 8192 }      /* DEM_DID_DIDCLASS_DID_0X2000 */ \
   ,{ 32, 8448 }      /* DEM_DID_DIDCLASS_DID_0X2100 */ \
}

#define DEM_CFG_ENVDID_ARRAYLENGTH  (2+1)


#endif

