/**************************************************************************************************\
 *** 
 *** Simulink model       : EPSControlLogic
 *** TargetLink subsystem : EPSControlLogic/EPS_TL
 *** Codefile             : EPS_TL_lut.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-02-25 18:10:24
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Efficient vector handling                : enabled
 *** Loop unroll threshold                    : 5
 *** Variable vector widths                   : enabled
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** No assignment of boolean expressions     : disabled
 *** Scope reduction only to function level   : enabled
 *** Exploit ranges if not erasable           : enabled
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : enabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : D:\TargetLink 3.3\Matlab\Tl\Config\codegen\cconfig.x
 ***                                            ml
 *** Root style sheet                         : D:\TargetLink 3.3\Matlab\Tl\XML\CodeGen\Stylesheets\
 ***                                            TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 3.3 from 24-Nov-2011
 *** Code generator version  : Build Id 3.3.0.57 from 2011-11-01 22:50:19
 *** Copyright (c) 2011 dSPACE GmbH
\**************************************************************************************************/

#ifndef EPS_TL_LUT_H
#define EPS_TL_LUT_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "rtwtypes.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/

#ifndef _MAP_Tab1DS0I2T2081_a_TYPE_
#define _MAP_Tab1DS0I2T2081_a_TYPE_
typedef struct MAP_Tab1DS0I2T2081_a_tag {
   UInt8 Nx;
   const UInt16 * x_table;
   const Int16 * z_table;
} MAP_Tab1DS0I2T2081_a;
#endif /* MAP_Tab1DS0I2T2081_a_TYPE_ */
#ifndef _MAP_Tab1DS0I2T2084_a_TYPE_
#define _MAP_Tab1DS0I2T2084_a_TYPE_
typedef struct MAP_Tab1DS0I2T2084_a_tag {
   UInt8 Nx;
   const Int16 * x_table;
   const Int16 * z_table;
} MAP_Tab1DS0I2T2084_a;
#endif /* MAP_Tab1DS0I2T2084_a_TYPE_ */
#ifndef _MAP_Tab1DS0I2T521_a_TYPE_
#define _MAP_Tab1DS0I2T521_a_TYPE_
typedef struct MAP_Tab1DS0I2T521_a_tag {
   UInt8 Nx;
   const UInt16 * x_table;
   const UInt16 * z_table;
} MAP_Tab1DS0I2T521_a;
#endif /* MAP_Tab1DS0I2T521_a_TYPE_ */
#ifndef _MAP_Tab1DS0I2T524_a_TYPE_
#define _MAP_Tab1DS0I2T524_a_TYPE_
typedef struct MAP_Tab1DS0I2T524_a_tag {
   UInt8 Nx;
   const Int16 * x_table;
   const UInt16 * z_table;
} MAP_Tab1DS0I2T524_a;
#endif /* MAP_Tab1DS0I2T524_a_TYPE_ */
#ifndef _MAP_Tab2DS0I2T16673_a_TYPE_
#define _MAP_Tab2DS0I2T16673_a_TYPE_
typedef struct MAP_Tab2DS0I2T16673_a_tag {
   UInt8 Nx;
   UInt8 Ny;
   const UInt16 * x_table;
   const Int16 * y_table;
   const Int16 * z_table;
} MAP_Tab2DS0I2T16673_a;
#endif /* MAP_Tab2DS0I2T16673_a_TYPE_ */
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   GlobalLookup1D_a: Derived TL_CG default function class.
\******************************************************************************/
extern Int16 Tab1DS0I2T2081_a(const MAP_Tab1DS0I2T2081_a * map, UInt16 x);
extern Int16 Tab1DS0I2T2084_a(const MAP_Tab1DS0I2T2084_a * map, Int16 x);
extern UInt16 Tab1DS0I2T521_a(const MAP_Tab1DS0I2T521_a * map, UInt16 x);
extern UInt16 Tab1DS0I2T524_a(const MAP_Tab1DS0I2T524_a * map, Int16 x);
extern Int16 Tab2DS0I2T16673_a(const MAP_Tab2DS0I2T16673_a * map, UInt16 x, Int16 y);


#endif/*EPS_TL_LUT_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
