/** @file     ASW_COM_MemMap.h
  *
  * @brief    RTE Sample SWC MemMap file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  *
  * @note     Suppressed errors detected.
  *           E002118, E002118, E002118
  */

#if defined (START_WITH_IF)
#elif defined(ASW_COM_START_SEC_CODE)
#undef ASW_COM_START_SEC_CODE
#define RTE_START_SEC_APPL_CODE
#elif defined(ASW_COM_STOP_SEC_CODE)
#undef ASW_COM_STOP_SEC_CODE
#define RTE_STOP_SEC_APPL_CODE
#elif defined (ASW_SHARE_DATA_COM_START_SEC)
#undef ASW_SHARE_DATA_COM_START_SEC
#define RTE_START_SEC_APPL_SHARE_DATA
#elif defined (ASW_SHARE_DATA_COM_STOP_SEC)
#undef ASW_SHARE_DATA_COM_STOP_SEC
#define RTE_STOP_SEC_APPL_SHARE_DATA
#elif defined (ASW_SHARE_CODE_COM_START_SEC)
#undef ASW_SHARE_CODE_COM_START_SEC
#define RTE_START_SEC_APPL_SHARE_CODE
#elif defined (ASW_SHARE_CODE_COM_STOP_SEC)
#undef ASW_SHARE_CODE_COM_STOP_SEC
#define RTE_STOP_SEC_APPL_SHARE_CODE
#elif defined (ASW_PRIVITE_DATA_COM_START_SEC)
#undef ASW_PRIVITE_DATA_COM_START_SEC
#define RTE_START_SEC_APPL_PRIVITE_DATA0
#elif defined (ASW_PRIVITE_DATA_COM_STOP_SEC)
#undef ASW_PRIVITE_DATA_COM_STOP_SEC
#define RTE_STOP_SEC_APPL_PRIVITE_DATA0
#elif defined (ASW_PRIVITE_CODE_COM_START_SEC)
#undef ASW_PRIVITE_CODE_COM_START_SEC
#define RTE_START_SEC_APPL_PRIVITE_CODE0
#elif defined (ASW_PRIVITE_CODE_COM_STOP_SEC)
#undef ASW_PRIVITE_CODE_COM_STOP_SEC
#define RTE_STOP_SEC_APPL_PRIVITE_CODE0
// #else
// #error "lack update memmap define"
#endif /* START_WITH_IF */

#include "Rte_MemMap.h"

