

#ifndef FEE_CFG_BLOCKDEFINES_H
#define FEE_CFG_BLOCKDEFINES_H

/* ####### Block defines of Fee instance 0 ####### */
#ifndef FEE_H
#define FeeConf_FeeBlockConfiguration_NvM_BR_AngCorrectStored                                        (0u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_4                                             (1u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_5                                             (2u)
#define FeeConf_FeeBlockConfiguration_NV_ValidityFlagsBlock                                          (3u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_ResetFlag                                               (4u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_7                                             (5u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_6                                             (6u)
#define FeeConf_FeeBlockConfiguration_NV_PartNumberBlock                                             (7u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_VehicleConfig                                           (8u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_CommonCRCStored                                         (9u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_TOCStudyTrq                                             (10u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_CCPVal                                                  (11u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_1                                             (12u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_0                                             (13u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_18                                            (14u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_29                                            (15u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_39                                            (16u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_2                                             (17u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_3                                             (18u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_19                                            (19u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_38                                            (20u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_28                                            (21u)
#define FeeConf_FeeBlockConfiguration_NvMBlockDescriptor_DID_SystemFaultRank                         (22u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_DEM_GENERIC_NV_DATA                                     (23u)
#define FeeConf_FeeBlockConfiguration_NV_ProgrammingCounterBlock                                     (24u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_TestMode                                                (25u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVT_STATUSBYTE                                          (26u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_VehicleName                                             (27u)
#define FeeConf_FeeBlockConfiguration_NV_CrcBlock                                                    (28u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_StrAngZero                                              (29u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_9                                             (30u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_8                                             (31u)
#define FeeConf_FeeBlockConfiguration_NvM_ConfigId                                                   (32u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_FunConfig                                               (33u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_CurrentOffset                                           (34u)
#define FeeConf_FeeBlockConfiguration_NV_ExternalReprogrammingRequestFlagBlock                       (35u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_31                                            (36u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_21                                            (37u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_10                                            (38u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_AngValidEnd                                             (39u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_20                                            (40u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_30                                            (41u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_11                                            (42u)
#define FeeConf_FeeBlockConfiguration_NvM_BN_DID_D09A                                                (43u)
#define FeeConf_FeeBlockConfiguration_NvMBlockDescriptor_ReadWritebyAddress                          (44u)
#define FeeConf_FeeBlockConfiguration_NvMBlockDescriptor_DID_IOControl                               (45u)
#define FeeConf_FeeBlockConfiguration_NvM_NativeBlock_2                                              (46u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_12                                            (47u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_33                                            (48u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_23                                            (49u)
#define FeeConf_FeeBlockConfiguration_NvMBlockDescriptor_DID_VehicleSpeed                            (50u)
#define FeeConf_FeeBlockConfiguration_NvM_NativeBlock_3                                              (51u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_13                                            (52u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_22                                            (53u)
#define FeeConf_FeeBlockConfiguration_NV_ProgrammingAttemptCounterBlock                              (54u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_32                                            (55u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_34                                            (56u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_24                                            (57u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_15                                            (58u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_InitAngle                                               (59u)
#define FeeConf_FeeBlockConfiguration_NvM_NATIVE_IDS_1024                                            (60u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_25                                            (61u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_35                                            (62u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_RotorOffset                                             (63u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_14                                            (64u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_Mileage                                                 (65u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_BackupConfig                                            (66u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_PenProf                                                 (67u)
#define FeeConf_FeeBlockConfiguration_NvM_BN_DID_F190                                                (68u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_SoftwareConfig                                          (69u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_17                                            (70u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_36                                            (71u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_AngEndCalData                                           (72u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_26                                            (73u)
#define FeeConf_FeeBlockConfiguration_NV_ResetResponseFlagBlock                                      (74u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_16                                            (75u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_27                                            (76u)
#define FeeConf_FeeBlockConfiguration_ECUM_CFG_NVM_BLOCK                                             (77u)
#define FeeConf_FeeBlockConfiguration_NVM_ID_EVMEM_LOC_37                                            (78u)
#define FeeConf_FeeBlockConfiguration_NvM_BR_VIN                                                     (79u)
#endif /* FEE_H */

#endif /* FEE_CFG_BLOCKDEFINES_H */
